[kijanikiosk]
api ansible_host=54.194.55.30
payments ansible_host=34.243.240.135
logs ansible_host=34.251.38.16

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../terraform/kijanikiosk-key.pem
