---
- name: Configure KijaniKiosk Servers
  hosts: kijanikiosk
  become: true

  handlers:
    - import_tasks: handlers/main.yml

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Nginx
      ansible.builtin.apt:
        name: "{{ nginx_package }}"
        state: present
      notify: Restart Nginx

    - name: Ensure Nginx is running
      ansible.builtin.systemd:
        name: "{{ nginx_service }}"
        state: started
        enabled: true
